INSERT INTO public.users (first_name, last_name, username, user_role, email, password) VALUES
    ('Havard', 'Naddardson', 'Lulu', 'ADMIN', 'havard.naddardson@mail.com', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Leah', 'Glutenstein', 'Lele', 'ADMIN', 'leah.glutenstein@mail.com', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),

    ('Lars', 'Stormborn', 'lstormborn', 'USER', 'lars.stormborn@valhalla.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Freya', 'Ironblade', 'fironblade', 'USER', 'freya.ironblade@midgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Bjorn', 'Wolfheart', 'bwolfheart', 'USER', 'bjorn.wolfheart@odinmail.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Astrid', 'Frostbane', 'afrostbane', 'USER', 'astrid.frostbane@valkyrie.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Erik', 'Shadowaxe', 'eshadowaxe', 'USER', 'erik.shadowaxe@nordrealm.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Ingrid', 'Lightbringer', 'ilightbringer', 'USER', 'ingrid.lightbringer@asgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Sven', 'Battleborn', 'sbattleborn', 'USER', 'sven.battleborn@storm.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Kari', 'Snowfall', 'ksnowfall', 'USER', 'kari.snowfall@fjordnet.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Magnus', 'Runecaster', 'mrunecaster', 'USER', 'magnus.runecaster@runic.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Helga', 'Ravenshield', 'hravenshield', 'USER', 'helga.ravenshield@odinmail.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Olaf', 'Ironfist', 'oironfist', 'USER', 'olaf.ironfist@valhalla.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Sigrid', 'Stormveil', 'sstormveil', 'USER', 'sigrid.stormveil@midgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Leif', 'Nightwolf', 'lnightwolf', 'USER', 'leif.nightwolf@nordrealm.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Thora', 'Iceborn', 'ticeborn', 'USER', 'thora.iceborn@valkyrie.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Harald', 'Blizzard', 'hblizzard', 'USER', 'harald.blizzard@storm.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Eira', 'Moonblade', 'emoonblade', 'USER', 'eira.moonblade@asgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Torvald', 'Skyrimsson', 'tskyrimsson', 'USER', 'torvald.skyrimsson@dragonborn.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Nora', 'Silveraxe', 'nsilveraxe', 'USER', 'nora.silveraxe@fjordnet.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Rune', 'Dragonbane', 'rdragonbane', 'USER', 'rune.dragonbane@runic.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Alva', 'Frostwind', 'afrostwind', 'USER', 'alva.frostwind@midgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Vidar', 'Stormrage', 'vstormrage', 'USER', 'vidar.stormrage@valhalla.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Liv', 'Nightshade', 'lnightshade', 'USER', 'liv.nightshade@nordrealm.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Axel', 'Thunderaxe', 'athunderaxe', 'USER', 'axel.thunderaxe@storm.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Saga', 'Iceveil', 'siceveil', 'USER', 'saga.iceveil@valkyrie.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Odin', 'Gamefather', 'ogamefather', 'USER', 'odin.gamefather@asgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Hilda', 'Runeheart', 'hruneheart', 'USER', 'hilda.runeheart@runic.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Arne', 'Pixelsson', 'apixelsson', 'USER', 'arne.pixelsson@midgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Knut', 'Raidmaster', 'kraidmaster', 'USER', 'knut.raidmaster@valhalla.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Mira', 'Stormsong', 'mstormsong', 'USER', 'mira.stormsong@asgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Ivar', 'Nordbyte', 'inordbyte', 'USER', 'ivar.nordbyte@nordrealm.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Ylva', 'Snowbyte', 'ysnowbyte', 'USER', 'ylva.snowbyte@fjordnet.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Sten', 'Arcadeborn', 'sarcadeborn', 'USER', 'sten.arcadeborn@storm.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Tove', 'Gameblade', 'tgameblade', 'USER', 'tove.gameblade@valhalla.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Einar', 'Frostpixel', 'efrostpixel', 'USER', 'einar.frostpixel@midgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Runa', 'Valhallaquest', 'rvalhallaquest', 'USER', 'runa.valhallaquest@asgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Baldur', 'Questborn', 'bquestborn', 'USER', 'baldur.questborn@nordrealm.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Sif', 'Stormquest', 'sstormquest', 'USER', 'sif.stormquest@valkyrie.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Tor', 'Thunderbyte', 'tthunderbyte', 'USER', 'tor.thunderbyte@storm.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Elin', 'Fjordblade', 'efjordblade', 'USER', 'elin.fjordblade@fjordnet.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Halvar', 'Nordgamer', 'hnordgamer', 'USER', 'halvar.nordgamer@midgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Greta', 'Icegamer', 'gicegamer', 'USER', 'greta.icegamer@valhalla.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Ulf', 'Runemaster', 'urunemaster', 'USER', 'ulf.runemaster@runic.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Solveig', 'Dragonpixel', 'sdragonpixel', 'USER', 'solveig.dragonpixel@dragonborn.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Hakon', 'Valhalladev', 'hvalhalladev', 'USER', 'hakon.valhalladev@asgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),

    -- ORGANIZERS (4)
    ('Ragnar', 'Eventborn', 'reventborn', 'ORGANIZER', 'ragnar.eventborn@valhalla.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Freydis', 'Lanmaster', 'flanmaster', 'ORGANIZER', 'freydis.lanmaster@midgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Sigurd', 'Tournamentaxe', 'stournamentaxe', 'ORGANIZER', 'sigurd.tournamentaxe@nordrealm.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),
    ('Yrsa', 'Guildleader', 'yguildleader', 'ORGANIZER', 'yrsa.guildleader@asgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.'),

    -- ADMIN (1)
    ('Thor', 'Allfather', 'tallfather', 'ADMIN', 'thor.allfather@asgard.gg', '$2y$10$.qkbukzzX21D.bqbI.B2R.tvWP90o/Y16QRWVLodw51BHft7ZWbc.');