DROP TABLE IF EXISTS em_event_category_join;
DROP TABLE IF EXISTS em_events;
DROP TABLE IF EXISTS em_event_category;

CREATE TABLE em_event_category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50),
    CONSTRAINT pk_em_event_category PRIMARY KEY (id)
);

ALTER TABLE em_event_category
    ADD CONSTRAINT constraint_eventcat_name UNIQUE (name);

CREATE TABLE em_events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50),
    description VARCHAR(255),
    state       VARCHAR(20),
    all_day     BOOLEAN,
    start_date  TIMESTAMP,
    end_date    TIMESTAMP,
    CONSTRAINT pk_em_events PRIMARY KEY (id)
);

CREATE TABLE em_event_category_join
(
    event_category_id BIGINT NOT NULL,
    event_id          BIGINT NOT NULL,
    CONSTRAINT pk_event_category_join PRIMARY KEY (event_category_id, event_id)
);

ALTER TABLE em_event_category_join
    ADD CONSTRAINT fk_evecatjoi_on_event FOREIGN KEY (event_id) REFERENCES em_events (id);

ALTER TABLE em_event_category_join
    ADD CONSTRAINT fk_evecatjoi_on_event_category FOREIGN KEY (event_category_id) REFERENCES em_event_category (id);